//
// Created by fgle on 18-10-9.
//

#ifndef INTRODUTIONTOALGORITHMS_INSERTIONSORT_H
#define INTRODUTIONTOALGORITHMS_INSERTIONSORT_H
void InsertionSort(int*, int);
#endif //INTRODUTIONTOALGORITHMS_INSERTIONSORT_H
